"""Add Units, UnitVersions and UnitChanges

Revision ID: 9790509bb96f
Revises:
Create Date: 2019-10-04 01:03:41.609873+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9790509bb96f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_sqlite():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'units',
        sa.Column('created_by', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('modified_by', sa.String(length=64), nullable=True),
        sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=True),
        sa.Column('wiki_path', sa.String(length=64), nullable=True),
        sa.Column('image_url', sa.String(length=128), nullable=True),
        sa.Column('panel_url', sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_table(
        'unit_changes',
        sa.Column('created_by', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('modified_by', sa.String(length=64), nullable=True),
        sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('unit_id', sa.Integer(), nullable=True),
        sa.Column('day', sa.Date(), nullable=True),
        sa.Column('description', sa.String(length=1024), nullable=True),
        sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    op.create_table(
        'unit_versions',
        sa.Column('created_by', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('modified_by', sa.String(length=64), nullable=True),
        sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('unit_id', sa.Integer(), nullable=True),
        sa.Column('gold', sa.Integer(), nullable=True),
        sa.Column('green', sa.Integer(), nullable=True),
        sa.Column('blue', sa.Integer(), nullable=True),
        sa.Column('red', sa.Integer(), nullable=True),
        sa.Column('energy', sa.Integer(), nullable=True),
        sa.Column('attack', sa.Integer(), nullable=True),
        sa.Column('health', sa.Integer(), nullable=True),
        sa.Column('supply', sa.Integer(), nullable=True),
        sa.Column('unit_spell', sa.String(length=32), nullable=True),
        sa.Column('frontline', sa.Boolean(), nullable=True),
        sa.Column('fragile', sa.Boolean(), nullable=True),
        sa.Column('blocker', sa.Boolean(), nullable=True),
        sa.Column('prompt', sa.Boolean(), nullable=True),
        sa.Column('stamina', sa.Integer(), nullable=True),
        sa.Column('lifespan', sa.Integer(), nullable=True),
        sa.Column('build_time', sa.Integer(), nullable=True),
        sa.Column('exhaust_turn', sa.Integer(), nullable=True),
        sa.Column('exhaust_ability', sa.Integer(), nullable=True),
        sa.Column('position', sa.String(length=32), nullable=True),
        sa.Column('abilities', sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade_sqlite():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unit_versions')
    op.drop_table('unit_changes')
    op.drop_table('units')
    # ### end Alembic commands ###
